language: go

os:
  - linux

go:
  - 1.13.x
  - master

go_import_path: github.com/syberalexis/automirror

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: dist/automirror*
  skip_cleanup: true
  on:
    tags: true