language: go

os:
  - linux
  - osx

go:
  - 1.13.x
  - master

go_import_path: github.com/syberalexis/automirror

after_script:
  - ls

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: automirror*
  skip_cleanup: true
  on:
    tags: true