dist = "stretch,stretch-updates,stretch-backports"
arch = "amd64"
section = "main,contrib,non-free,main/debian-installer"
root = "/debian"
method = "http"
keyring = "/usr/share/keyrings/debian-archive-keyring.gpg"
cleanup = false
source = true
i18n = true
options = "--progress"