log:
  dir: 'tmp/log/'
#  format: 'json'
#  level: 'debug'
mirrors:
  clamav-main:
#    timer: '10s'
    engine:
      name: 'wget'
      config: 'examples/clamav-main.yaml'
      archives:
        - name: 'http://database.clamav.net/main.cvd'
