dist = "testing"
arch = "amd64"
section = "main,contrib,non-free,main/debian-installer"
root = "/debian"
method = "http"
keyring = "/usr/share/keyrings/debian-archive-keyring.gpg"
cleanup = false
source = false
i18n = true
options = "--progress --ignore-release-gpg"