source = "https://registry-1.docker.io/v2"
destination = "./tmp/docker"
auth_uri = "https://auth.docker.io/token?service=registry.docker.io"
[[images]]
    name = "alpine"
[[images]]
    name = "centos"
[[images]]
    name = "ubuntu"