host = "archive.ubuntu.com"
destination = "./tmp/ubuntu"
dist = "disco,disco-security,disco-updates,disco-backports"
arch = "amd64"
section = "main,restricted,universe,multiverse"
root = "/ubuntu"
method = "http"
keyring = "/usr/share/keyrings/ubuntu-archive-keyring.gpg"
cleanup = false
source = true
i18n = true
options = "--progress"